cmake_minimum_required(VERSION 3.8)
project(algorithm)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include_directories("${PROJECT_SOURCE_DIR}/Graph")
include_directories("${PROJECT_SOURCE_DIR}/Utils")
include_directories("${PROJECT_SOURCE_DIR}/Greedy")
include_directories("${PROJECT_SOURCE_DIR}/Huffman")
include_directories("${PROJECT_SOURCE_DIR}/MWis")
include_directories("${PROJECT_SOURCE_DIR}/Knapsack")
include_directories("${PROJECT_SOURCE_DIR}/AllPairs")
include_directories("${PROJECT_SOURCE_DIR}/Tsp")
include_directories("${PROJECT_SOURCE_DIR}/HeuristicTsp")
add_subdirectory(Graph)
add_subdirectory(Utils)
add_subdirectory(Greedy)
add_subdirectory(Huffman)
add_subdirectory(MWis)
add_subdirectory(Knapsack)
add_subdirectory(AllPairs)
add_subdirectory(Tsp)
add_subdirectory(HeuristicTsp)

add_executable(algorithm main.cpp)
target_link_libraries(algorithm Graph Utils Greedy Huffman MWis Knapsack AllPairs Tsp HeuristicTsp)